#文章展示动画
wowjs:
  enable: false #控制动画开关。true是打开，false是关闭
  priority: 10 #过滤器优先级
  mobile: false #移动端是否启用，默认移动端禁用
  animateitem:
  - class: recent-post-item #必填项，需要添加动画的元素的class
    style: animate__fadeInUp #必填项，需要添加的动画
    duration: 0.5s #选填项，动画持续时间，单位可以是ms也可以是s。例如3s，700ms。
    delay: 0 #选填项，动画开始的延迟时间，单位可以是ms也可以是s。例如3s，700ms。
    offset: 50 #选填项，开始动画的距离（相对浏览器底部）
    iteration: 1 #选填项，动画重复的次数
  - class: card-widget
    style: animate__fadeInUp
  animate_css: https://npm.elemecdn.com/hexo-butterfly-wowjs/lib/animate.min.css
  wow_js: https://npm.elemecdn.com/hexo-butterfly-wowjs/lib/wow.min.js
  wow_init_js: https://npm.elemecdn.com/hexo-butterfly-wowjs/lib/wow_init.js
# --------------------------------------
# 导航设置
# --------------------------------------
nav:
  # 导航栏 Logo 图片
  logo:
  # 是否显示标题
  display_title: true
  # 是否固定导航栏
  fixed: false
menu:
  首页: / || fas fa-home
  # 时间轴: /archives/ || fas fa-archive
  # 标签: /tags/ || fas fa-tags
  # 分类: /categories/ || fas fa-folder-open
  友人帐: /link/ || fas fa-link
  留言信: /comments/ || fas fa-envelope
  关于: /about/ || fas fa-heart
# 社交媒体链接
# 格式: icon: 链接 || 描述 || 颜色
social:
  fab fa-github: https://github.com/hearthitagi || Github
  fas fa-envelope: mailto:1760603940@qq.com || Email

# --------------------------------------
# 代码块设置
# --------------------------------------
highlight_theme: light #  darker / pale night / light / ocean / mac / mac light / false
highlight_copy: true # copy button
highlight_lang: true # show the code language
highlight_shrink: false # true: shrink the code blocks / false: expand the code blocks | none: expand code blocks and hide the button
highlight_height_limit: 450 # unit: px
code_word_wrap: false
snackbar:
  enable: true
  position: bottom-left
  bg_light: '#49b1f5' 
  bg_dark: '#121212'

# --------------------------------------
# 图片设置
# --------------------------------------
# 网站的 favicon 图标
favicon: /img/favicon.svg
# 头像设置
avatar:
  # 头像图片链接
  img: https://img.hitagi.site/avatar-1.png
  # 是否启用头像效果
  effect: false
# 网站背景 可以设置为颜色或图片
background: url(https://img.hitagi.site/e0d615a6-6507-4334-9758-718130984d26.webp)
# 主页背景图
index_img:
# 默认顶部图
default_top_img: transparent
# 时间轴(归档)顶部图
archive_img: false
# 子标签顶部图 (不设置即为默认顶部图)
tag_img: false
# 子分类页面顶部图 (不设置即为默认顶部图)
category_img: false
# 每个标签的顶部图
tag_per_img: false
# 每个分类的顶部图
category_per_img: false
# 禁用所有背景图片
disable_top_img: false
# 页脚背景图
footer_bg: false

# 封面设置
cover:
  # 是否禁用封面
  index_enable: true
  aside_enable: true
  # 主页封面的位置
  # 选择: left/right/both
  position: both
  # 当未设置封面时，显示默认封面
  default_cover:
    - https://img.hitagi.site/202211142223334.jpg
# 替换损坏的图片
error_img:
  # 友链页面的错误图片
  flink: /img/friend_404.gif
  # 文章页面的错误图片
  post_page: /img/404.jpg
# 简单的 404 页面
error_404:
  # 是否启用 404 页面
  enable: false
  # 404 页面的副标题
  subtitle: 'Page Not Found'
  # 404 页面的卡片背景图片
  background: https://i.loli.net/2020/05/19/aKOcLiyPl2JQdFD.png
# 文章元数据设置
post_meta:
  page: # 主页页面
    date_type: created # 日期类型: created / updated / both
    date_format: date # 日期格式: date / relative
    categories: true # 是否显示分类
    tags: true # 是否显示标签
    label: true # 是否显示描述文字
  post:
    date_type: both # 日期类型: created / updated / both
    date_format: date # 日期格式: date / relative
    categories: true # 是否显示分类
    tags: true
    label: true 

# --------------------------------------
# 首页设置
# --------------------------------------
# 在首页显示文章简介 1: 描述
index_post_content:
  method: 1
# 加载动画
preloader:
  enable: true # true|false
  load_color: '#37474f'  # '#37474f'
  load_style: wizard # default|wizard|
  load_image:  # url
# 标题字体
blog_title_font:
  font_link: https://fonts.googleapis.com/css?family=Playball&display=swap
  font-family: Playball

# --------------------------------------
# 文章设置
# --------------------------------------
toc:
  # 是否在文章中显示目录
  post: true
  # 是否在页面中显示目录
  page: false
  # 是否显示目录编号
  number: true
  # 是否默认展开目录
  expand: false
  # 是否使用简洁风格（仅适用于文章）
  style_simple: false
post_copyright:
  # 是否启用版权声明
  enable: true
  # 是否进行文章 URL 解码
  decode: true
  # 作者链接
  author_href: https://hitagi.site/
  # 许可证类型
  license: CC BY-NC-SA 4.0
  # 许可证链接
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
# 打赏
reward:
  # 是否启用打赏
  enable: true
  QR_code:
    - img: https://img.hitagi.site/reward-wx.png
      link:
      text: 微信
    - img: https://img.hitagi.site/reward-ali.jpg
      link:
      text: 支付宝
# 相关文章
related_post:
  # 是否显示相关文章
  enable: true
  # 显示的文章数量
  limit: 3
  # 选择: created / updated
  date_type: updated
#分页
post_pagination: 2
# 显示文章过期通知
noticeOutdate:
  # 是否启用过期通知
  enable: true
  # 样式: simple / flat
  style: simple
  # 多少天后显示通知
  limit_day: 365
  # 位置: top / bottom
  position: top
  message_prev: 已经过了
  message_next: 天自上次更新，文章内容可能已过时。

# --------------------------------------
# 页脚设置
# --------------------------------------
footer:
  owner:
    # 是否启用所有者显示
    enable: true
    # 网站创建年份
    since: 2021
  # 自定义文本
  custom_text: Violet Evergarden
  # 主题和框架的版权声明
  copyright: true
# --------------------------------------
# 侧边栏设置
# --------------------------------------
aside:
  # 是否启用侧边栏
  enable: true
  # 是否默认隐藏侧边栏
  hide: false
  # 是否在右下角显示隐藏侧边栏的按钮
  button: true
  # 移动设备上是否启用侧边栏
  mobile: true
  # 侧边栏位置：left / right
  position: left
  card_author:
    # 是否显示作者信息卡片
    enable: true
    # 作者描述
    description: 不可结缘
    button:
      # 是否显示按钮
      enable: false
  card_announcement:
    # 是否显示公告卡片
    enable: false
    # 公告内容
    content: This is my Blog
  card_recent_post:
    # 是否显示最近文章卡片
    enable: false
    # 显示文章数量，0 表示显示所有
    limit: 5
    # 排序方式：date / updated
    sort: date
    sort_order:
  card_newest_comments:
    # 是否显示最新评论卡片
    enable: false
    sort_order:
    # 显示评论数量
    limit: 5
    # 单位：分钟，保存数据到 localStorage
    storage: 10
    # 是否显示头像
    avatar: true
  card_categories:
    # 是否显示分类卡片
    enable: false
    # 显示分类数量，0 表示显示所有
    limit: 8
    # 选择：none / true / false
    expand: none
    sort_order:
  card_tags:
    # 是否显示标签卡片
    enable: true
    # 显示标签数量，0 表示显示所有
    limit: 0
    # 是否启用颜色
    color: false
    # 标签排序方式：random/name/length
    orderby: name
    # 排序顺序：1 表示升序，-1 表示降序
    order: 1
    sort_order:
  card_archives:
    # 是否显示归档卡片
    enable: false
    # 归档类型：monthly / yearly
    type: monthly
    # 日期格式，例如：YYYY年MM月
    format: MMMM YYYY
    # 排序顺序：1 表示升序，-1 表示降序
    order: -1
    # 显示归档数量，0 表示显示所有
    limit: 8
    sort_order:
  card_post_series:
    # 是否显示系列文章卡片
    enable: true
    # 标题显示系列名称
    series_title: false
    # 排序方式：title 或 date
    orderBy: 'date'
    # 排序顺序：1 表示升序，-1 表示降序
    order: -1
  card_webinfo:
    # 是否显示网站信息卡片
    enable: true
    # 是否显示文章数量
    post_count: true
    # 是否显示最后推送日期
    last_push_date: true
    sort_order:
# 最新评论
newest_comments:
  enable: true
  sort_order:
  limit: 5
  storage: 10 # unit: mins, save data to localStorage
  avatar: true
# --------------------------------------
# 右下角按钮设置
# --------------------------------------
# 右下角按钮与底部的距离（默认单位：px）
rightside_bottom:
# 简繁转换设置
translate:
  # 是否启用简繁转换
  enable: false
# 阅读模式
readmode: true
# 暗黑模式设置
darkmode:
  # 是否启用暗黑模式
  enable: true
  # 切换暗黑/明亮模式的按钮
  button: true
  # 是否自动切换暗黑/明亮模式
  autoChangeMode: 1
  # 设置明亮模式时间，值在 0 到 24 之间。如果未设置，默认值为 6 和 18
  start: 6
  end: 24
# 在返回顶部按钮中显示滚动百分比
rightside_scroll_percent: false
# 右下角按钮与底部距离
rightside-bottom:

# --------------------------------------
# 全局设置
# --------------------------------------
# 锚点设置
anchor: false
# 图片描述文字
photofigcaption: false
# 复制设置
copy:
  # 是否启用复制功能
  enable: true
  # 在复制的内容后添加版权信息
  copyright:
    enable: false
    # 当复制字符数超过 limit_count 时添加版权信息
    limit_count: 150
# 开启网页进入效果
enter_transitions: true
# 字体
font:
  global-font-size:
  code-font-size:
  font-family:
  code-font-family:
# --------------------------------------
# 搜索设置
# --------------------------------------
local_search:
  enable: true
  preload: true
# --------------------------------------
# 评论系统
# --------------------------------------
comments:
  use: waline
  text: false # 是否显示评论服务商的名字
  lazyload: false
  count: false # 是否在文章顶部显示评论数
  card_post_count: false # 是否在首页文章卡片显示评论数
# waline
waline:
  serverURL: https://comment.hitagi.site
  bg: https://img.hitagi.site/pinglun.webp
  pageview: false
  option:
    imageUploader: true

# --------------------------------------
# 页面美化
# --------------------------------------
# theme_color:
#   enable: true
#   main: "#49B1F5"
#   paginator: "#00c4b6"
#   button_hover: "#FF7242"
#   text_selection: "#00c4b6"
#   link_color: "#99a9bf"
#   meta_color: "#858585"
#   hr_color: "#A4D8FA"
#   code_foreground: "#F47466"
#   code_background: "rgba(27, 31, 35, .05)"
#   toc_color: "#00c4b6"
#   blockquote_padding_color: "#49b1f5"
#   blockquote_background_color: "#49b1f5"
  scrollbar_color: "#f7f9fe"
# 美化显示
beautify:
  enable: true
  field: site # site/post
  title-prefix-icon: '\f0c1'
  title-prefix-icon-color: '#F47466'

# --------------------------------------
# 其他设置
# --------------------------------------
#图片预览
fancybox: true
# 水平线分割
hr_icon:
  enable: true
  icon: # the unicode value of Font Awesome icon, such as '\3423'
  icon-top:
# 网站运行时间
runtimeshow:
  enable: true
  publish_date: 1/26/2022 14:23:31
# 标签外挂
mermaid:
  enable: false
  # built-in themes: default/forest/dark/neutral
  theme:
    light: default
    dark: dark
# 中英文空格
pangu:
  enable: true
  field: site # site/post
# 预加载
instantpage: true
# 图片懒加载
lazyload:
  enable: true
  field: site # site/post
  placeholder:
  blur: false
Open_Graph_meta: true
# Note (Bootstrap Callout)
note:
  style: flat
  icons: true
  border_radius: 3
  light_bg_offset: 0
# --------------------------------------
# 自定义内容
# --------------------------------------
# 留言信
envelope_comment:
  enable: true #开关
  cover: https://npm.elemecdn.com/hexo-butterfly-envelope/lib/violet.jpg #信笺封面图
  message: #信笺内容，支持多行
    - “为什么要写信”
    - “因为人有心意想传达给别人”
  bottom: 自动书记人偶 Violet Evergarden
  height: #调整信笺划出高度，默认1050px
#分类磁贴
categoryBar:
  enable: true # 开关
  message:
  - title: 电子杂物
    cover: https://img.hitagi.site/categories-1.jpg
    descr: 这是电子杂物描述
  - title: 博客相关
    cover: https://img.hitagi.site/categories-2.jpg
    descr: 这是博客相关描述
  - title: 前端知识
    cover: https://img.hitagi.site/categories-3.jpg
    descr: 这是前端知识描述
inject:
  head:
  - <link rel="stylesheet" href="/css/custom.css" media="defer" onload="this.media='all'">
  bottom:
  - <script async data-pjax src="/js/selectBg.js"></script>
  - <script async data-pjax src="/js/dark.js"></script>